- config_name : "BDPostgress"
  user : "admin"
  password : "admin123"
  hostname : "postgres-app" #"postgres-app"
  port : "5432"
  database : "project_airflow"

- config_name : "BDPostgres25"
  user : "admin"
  password : "admin123"
  hostname : "postgres-app" #"postgres-app"
  port : "5432"
  database : "project_airflow"