from enum import Enum

class StatusFile(Enum):
    UPLOADED_FILE = 'UPLOADED_FILE'
    ERROR_UPLOADING = 'ERROR_UPLOADING'
    UNZIPPED = 'UNZIPPED'
    ERROR_UNZIPPED = 'ERROR_UNZIPPED'
    CREATED = 'CREATED'
    ERROR_CREATED = 'ERROR_CREATED'
